#!/bin/bash
allThreads=("database.csv" "package.json" "babel.config.js" ".eslintrc.js" "0-console.js" "1-stdin.js" "2-read_file.js" "3-read_file_async.js" "4-http.js" "5-http.js" "6-http_express.js" "7-http_express.js" "full_server/utils.js" "full_server/controllers/AppController.js" "full_server/controllers/StudentsController.js" " full_server/routes/index.js" "full_server/server.js")

mkdir -p "0x05-Node_JS_basic"
mkdir -p "0x05-Node_JS_basic/full_server"
mkdir -p "0x05-Node_JS_basic/full_server/controllers"
mkdir -p "0x05-Node_JS_basic/full_server/routes"

for t in ${allThreads[@]}; do

    if [[ $t == *".py"* ]]; then
        echo -e "#!/usr/bin/python3\n" > "./0x05-Node_JS_basic/$t" && chmod +x "./0x05-Node_JS_basic/$t"
    else
        # echo -e "#!/usr/bin/node\n" > "./0x05-Node_JS_basic/$t"
        touch "./0x05-Node_JS_basic/$t"
    fi
done

echo -e "# ALX Programme Project: 0x05. NodeJS Basics" > "./0x05-Node_JS_basic/README.md"

echo -e "#!/bin/bash\ngit add . && git commit -m '0x05. NodeJS Basics' && git push"  > "./0x05-Node_JS_basic/correction" && chmod +x "./0x05-Node_JS_basic/correction"

cp "../alx-higher_level_programming/0x05-python-exceptions/clean_up_corrections" "./0x05-Node_JS_basic/"

cd ./0x05-Node_JS_basic
